Master <- Develop
Siama94/AppleMusic_SwiftUI pull request #15
Opened 2022-01-08 06:23 UTC by Siama94

2022-01-09 06:30 UTC, nskazakov requested changes

2022-01-09 06:30 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Library/View/EmptyLibraryView.swift
> +}
почему это тут? Мб вынести в отдельный файл?

2022-01-09 06:30 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Library/View/FilterLibraryView.swift
> +}
я не понял, почему это в отдельной структуре, а не в экстеншне? Можно же сделать экстеншн этой же структуры, туда добавить енам и там создать эти константы...

2022-01-09 06:30 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Radio/Model/StationsItemsModel.swift
> +extension StationItemsModels: Hashable {
что такое Hashable и для чего оно тут нужно?

2022-01-09 06:30 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Search/View/SearchResult.swift
> +extension SearchResult {
вот тут же делала через енам, почему в других файлах отдельную структуру создала?

2022-01-09 06:30 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Search/View/SearchMainView.swift
> +        count: Metric.columnsCount)
если открытие скобки на отдельной строке с первым параметром, значит закрытие скобки тоже должно быть на отдельной строке

2022-01-12 01:58 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Search/View/SearchMainView.swift
> +        count: Metric.columnsCount)
✅

2022-01-12 01:58 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Search/View/SearchResult.swift
> +extension SearchResult {
✅

2022-01-12 01:58 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Radio/Model/StationsItemsModel.swift
> +extension StationItemsModels: Hashable {
Generic struct 'ForEach' requires that 'StationItemsModels' conform to 'Hashable'. 

Такая ошибка потом будет во время  ForEach'а при передаче в него массива из StationItemsModels, если убираю  Hashable.

2022-01-12 01:58 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Library/View/FilterLibraryView.swift
> +}
✅

2022-01-12 01:58 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Library/View/EmptyLibraryView.swift
> +}
✅

2022-01-12 04:08 UTC, nskazakov requested changes

2022-01-12 04:08 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Library/View/EmptyLibraryView.swift
> +    static let bottomPaddingForTopText: CGFloat = 1
выравнивание странное какое-то)))

2022-01-12 04:08 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Library/View/FilterLibraryView.swift
> +    static let paddingForImage: CGFloat = 10
и тут
СМИСИ? Че это?
Я думал сверху это случайность была

2022-01-12 04:08 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Player/View/PlayerView.swift
> +    static let screenFractionImage: CGFloat = 3.5
выше писал про это

2022-01-12 04:08 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Search/View/SearchMainView.swift
> +}
а тут же норм с форматированием)))

2022-01-12 04:20 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Library/View/EmptyLibraryView.swift
> +    static let bottomPaddingForTopText: CGFloat = 1
✅

2022-01-12 04:20 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Library/View/FilterLibraryView.swift
> +    static let paddingForImage: CGFloat = 10
✅

2022-01-12 04:20 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Player/View/PlayerView.swift
> +    static let screenFractionImage: CGFloat = 3.5
✅

2022-01-14 03:33 UTC, merged