Create library and player.
Siama94/AppleMusic_SwiftUI pull request #5
Opened 2021-11-11 07:32 UTC by Siama94

2021-11-23 09:47 UTC, nskazakov requested changes

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Library/Model/FilterItemsModel.swift
> +extension FilterItemsModel: Hashable {
зачем тут Hashable?

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Player/View/PlayerView.swift
> +                    .frame(width: 55, height: 55)
Магические числа лучше в константы выносить

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Player/View/PlayerView.swift
> +                    .shadow(color: .gray, radius: 10, x: 0.0, y: 5.0)
и тут магические цифры, не особо понятно что они означают

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Player/View/PlayerView.swift
> +                        .padding(.trailing, 10)
и везде по файлам магические цифры надо убрать)))

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Player/View/PlayerView.swift
> +        .background(Color.init("GrayColor"))
????
init?
Color(...) или .init(...)

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Radio/Model/StationsItemsModel.swift
> +extension StationItemsModels: Hashable {
и тут Hashable. Зачем?))

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/Modules/Radio/Model/RadioItemsModel.swift
> +extension RadioItemsModel: Hashable {
и вот тут Hashable. Зачем?))

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/TabView/TabView.swift
> +        }
тут что-то с выравниванием

2021-11-23 09:47 UTC, nskazakov commented on AppleMusic_SwiftUI/TabView/TabView.swift
> +            }
тут тоже что-то с выравниванием

2021-11-30 01:00 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Library/Model/FilterItemsModel.swift
> +extension FilterItemsModel: Hashable {
<img width="712" alt="Снимок экрана 2021-11-29 в 6 27 29 PM" src="https://user-images.githubusercontent.com/85932767/143966541-ae35689a-29cb-48a8-84cc-fe80b03cb7d1.png">

2021-11-30 01:01 UTC, Siama94 commented on AppleMusic_SwiftUI/Modules/Library/Model/FilterItemsModel.swift
> +extension FilterItemsModel: Hashable {
Если убираю Hashable, то ошибка в ForEach потом

2021-11-30 01:03 UTC, closed without merging